### PR TITLE
Upgrade proto submodule to 1.1.1

### PR DESCRIPTION
**Pull request by TheKeveloper**
The proto in the submodule here seems to be fairly behind the current MAVSDK proto. This PR upgrades the proto to the latest tag (1.1.1). 

I haven't been able to test that this works though because I'm still trying to get the `generateProto` task running locally.

### CODE REVIEW

**Comment by JonasVautherin** [comment]
Thanks for the contribution!

However, that's not quite how it works. The versions there are mostly for [protoc-gen-mavsdk](https://pypi.org/project/protoc-gen-mavsdk/#history).

I try to point the proto submodule to the version corresponding to the mavsdk_server in use. Currently that would be the one used by mavsdk_server v1.4.11.

**Comment by TheKeveloper** [comment]
Hey @JonasVautherin thanks for the reply! Don't we want to upgrade that are generated by protoc-gen-mavsdk though? Because right now the mavsdk java client doesn't have the up to date protos, even if the underlying server has the up to date proto. 

I can file a separate issue for this, but for example, the generated `MissionItem` proto currently has no way to specify a `VehicleAction` even though that is currently supported in the proto: https://github.com/mavlink/MAVSDK-Proto/blob/main/protos/mission/mission.proto#L212

This also seems to be what @divyanshupundir has done in previous PRs: https://github.com/mavlink/MAVSDK-Java/commit/5fa32a2d06c0c7cdae87a1ba3230c30bd6d1f228. 

If this isn't the right way to update the client side protos, could you point me in the right direction? 

Thanks!

**Comment by JonasVautherin** [comment]
That's because `VehicleAction` is not in 1.4.13 yet (see [here](https://github.com/mavlink/MAVSDK-Proto/blob/17d707685a8cbe5e0b6c930850b5a2c75b85bbd8/protos/mission/mission.proto)). It will come with MAVSDK v2.

In the meantime, unfortunately you have to build from source if you want that feature :confused:.

**Comment by TheKeveloper** [comment]
Ah, thanks for clarifying! I didn't realize that VehicleAction was not implemented in the mavsdk server yet. Looking forward to MAVSDK v2!

**Comment by JonasVautherin** [comment]
> I didn't realize that VehicleAction was not implemented in the mavsdk server yet.

Actually, it is implemented in the `main` branch. But the `main` branch will release `v2`, whereas `v1.4.x` is older. So it is implemented, just not released yet, if that makes sense :innocent:

**Pull request closed without merging**
