### PR TITLE
fix: Updated examples/android-client according to the new api

### PR DESCRIPTION
**Pull request by jjcetraro**

### CODE REVIEW

**Comment by JonasVautherin** [comment]
Great, thanks @jjcetraro 

@divyanshu1234: would you mind reviewing? Also I invited you as collaborator in the repo, since you do contribute a lot, I think it is well deserved. If you want it of course :wink:

**Comment by divyanshu1234** [comment]
@JonasVautherin it'll be my pleasure and thanks for the invite.

I'll try to do it by EOD.

**Review by JonasVautherin — APPROVED** [review]

**Comment by divyanshu1234** [comment]
Preoccupied with some work. Will try to do it by tomorrow.

**Comment by divyanshu1234** [comment]
@jjcetraro Apart from some formatting (indentations) the code looks good. I'll try to run it one my phone by tonight.

**Comment by jjcetraro** [comment]
done!

**Pull request merged**
